Repository SquadHouseDev/SquadHouse, pull requests merged in 2021-04, with the labels that each got.

#19 Feature search page and follow
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SearchActivity.java
  app/src/main/java/com/pepetech/squadhouse/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/SearchAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/cell_found.xml
  docs/demo/v1.0.0-completed-follow-feature.gif
  docs/demo/v1.0.0-completed-unfollow-feature.gif
  docs/demo/v1.0.0-search-layout-demo.gif
  docs/wireframes/search-page.png
Labels: enhancement

#29 Improve documentation of the Interest class and fix accessor bugs
  app/src/main/java/com/pepetech/squadhouse/models/Club.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
Labels: bug, documentation, enhancement

#30 Feature search page and follow
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/SquadHouseApplication.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/LoginActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SignUpActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewAClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewAUserProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreClubAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreUserAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Club.java
  app/src/main/java/com/pepetech/squadhouse/models/Interest.java
  app/src/main/java/com/pepetech/squadhouse/models/InterestGroup.java
  app/src/main/java/com/pepetech/squadhouse/models/Room.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/drawable/cell_background.xml
  app/src/main/res/drawable/cursorcolor.xml
  app/src/main/res/layout/activity_club.xml
  app/src/main/res/layout/activity_explore.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_view_a_user_profile.xml
  app/src/main/res/layout/activity_view_my_profile.xml
  app/src/main/res/layout/cell_explore_found.xml
  app/src/main/res/layout/cell_explore_interest.xml
  app/src/main/res/layout/cell_home_room_active.xml
  app/src/main/res/layout/cell_home_room_future.xml
  app/src/main/res/layout/cell_home_search.xml
  app/src/main/res/values/strings.xml
  docs/demo/v1.0.0-basic-keyword-search-for-users-or-clubs.gif
  docs/demo/v1.0.0-basic-keyword-search-for-users.gif
  docs/demo/v1.0.0-color-scheme-consolidation.gif
  docs/demo/v1.0.0-completed-follow-feature.gif
  docs/demo/v1.0.0-completed-unfollow-feature.gif
  docs/demo/v1.0.0-demo.gif
  docs/demo/v1.0.0-explore-a-user-profile.gif
  docs/demo/v1.0.0-fix-interest-grouping.gif
  docs/demo/v1.0.0-fix-user-signup.gif
  docs/demo/v1.0.0-profile-show-nominator.gif
  docs/demo/v1.0.0-search-layout-demo.gif
  docs/demo/v1.0.0-search-page-cell-interest.gif
  docs/interest-csv-generator.ipynb
  docs/interests.csv
  docs/squad-house-class-diagram.uxf
  docs/wireframes/search-page.png
  docs/wireframes/view-a-user-profile.png
Labels: bug, documentation, enhancement

#34 Follow/Unfollow and Keyword Search Match Indifference Feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/SquadHouseApplication.java
  app/src/main/java/com/pepetech/squadhouse/activities/ClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreUserActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/LoginActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SettingsActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SignUpActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/WelcomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreClubAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreUserAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Club.java
  app/src/main/java/com/pepetech/squadhouse/models/Follow.java
  app/src/main/java/com/pepetech/squadhouse/models/InterestGroup.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/layout/activity_club.xml
  app/src/main/res/layout/activity_explore.xml
  app/src/main/res/layout/activity_explore_club_profile.xml
  app/src/main/res/layout/activity_explore_user_profile.xml
  app/src/main/res/layout/cell_explore_found.xml
  app/src/main/res/values/strings.xml
  docs/demo/v1.0.0-basic-keyword-search-for-users-or-clubs.gif
  docs/demo/v1.0.0-basic-keyword-search-for-users.gif
  docs/demo/v1.0.0-explore-and-follow-a-club.gif
  docs/demo/v1.0.0-explore-follow-and-unfollow-a-club.gif
  docs/demo/v1.0.0-explore-keyword-search-indifference.gif
  docs/demo/v1.0.0-fix-interest-grouping.gif
  docs/wireframes/explore-club.png
Labels: backend design, priority: high

#44 Feature profile page
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/BottomSheetDialogActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateFullNameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateUsernameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/layout/activity_popup_window.xml
  app/src/main/res/layout/bottom_sheet_layout.xml
  app/src/main/res/layout/update_fullname.xml
  app/src/main/res/layout/update_profileimage.xml
  app/src/main/res/layout/update_username.xml
  app/src/main/res/values/themes.xml
  docs/demo/full name edit.gif
  docs/wireframes/profile-editting.png
Labels: feature, frontend design

#42 Updated database design and applied fix for PR#40
  docs/squad-house-activity-class-included.uxf
  docs/squad-house-class-diagram.png
  docs/squad-house-class-diagram.uxf
Labels: backend design, documentation

#41 Basic Settings Activity Integration
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/SettingsActivity.java
  app/src/main/res/layout/activity_settings.xml
Labels: feature, frontend design, priority: high, sprintable

#46 Project Reorganize + Followers Activity + Followers Querying/Updating
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreUserActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/FollowersActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/adapters/ExploreClubAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/adapters/ExploreInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/adapters/ExploreUserAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Login/LoginActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Login/SignUpActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Login/WelcomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/BottomSheetDialogActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/SettingsActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/UpdateFullNameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/UpdateUsernameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/layout/activity_explore.xml
  app/src/main/res/layout/activity_explore_club_profile.xml
  app/src/main/res/layout/activity_explore_user_profile.xml
  app/src/main/res/layout/activity_followers.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_view_my_profile.xml
  app/src/main/res/layout/activity_welcome.xml
  docs/squad-house-class-diagram.uxf
Labels: backend design, feature, frontend design

#48 Fix typo in displaying number of followers
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreUserActivity.java
Labels: bug

#49 Interest display and lock to portrait
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/SettingsActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/InterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/SettingsActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/adapters/InnerInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/adapters/OuterInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Interest.java
  app/src/main/res/layout/activity_interest.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/cell_home_room_active.xml
  app/src/main/res/layout/cell_inner_rv_interest.xml
  app/src/main/res/layout/cell_interest_select.xml
  docs/squad-house-class-diagram.uxf
Labels: enhancement, feature, frontend design, priority: high, sprintable

#50 Add documentation and fix routing for button with added Toast
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/InterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/adapters/InnerInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/adapters/OuterInterestAdapter.java
  app/src/main/res/layout/activity_interest.xml
  app/src/main/res/layout/cell_interest_select.xml
  docs/squad-house-class-diagram.uxf
Labels: documentation, enhancement, frontend design

#51 Feature heterogeneous home page
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeMultiViewAdapter.java
  app/src/main/res/drawable/cell_darker_background.xml
  app/src/main/res/drawable/cell_white_background.xml
  app/src/main/res/drawable/ic_network.xml
  app/src/main/res/layout/cell_explore_interest.xml
  app/src/main/res/layout/cell_home_explore.xml
  app/src/main/res/layout/cell_home_room_active.xml
  app/src/main/res/layout/cell_home_room_future.xml
  app/src/main/res/layout/cell_home_search.xml
  app/src/main/res/layout/cell_interest_select.xml
  app/src/main/res/values/colors.xml
  build.gradle
  docs/demo/completed-heterogeneous-home-page.gif
  docs/demo/v1.0.0-hetero-recycler-home-page.gif
Labels: feature, frontend design, priority: high

#54 Feature profile page
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/SquadHouseApplication.java
  app/src/main/java/com/pepetech/squadhouse/activities/BottomSheetDialogActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ExploreUserActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/LoginActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SettingsActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SignUpActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateFullNameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/UpdateUsernameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewAClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/WelcomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreClubAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ExploreUserAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Club.java
  app/src/main/java/com/pepetech/squadhouse/models/Follow.java
  app/src/main/java/com/pepetech/squadhouse/models/User.java
  app/src/main/res/layout/activity_club.xml
  app/src/main/res/layout/activity_explore_club_profile.xml
  app/src/main/res/layout/activity_explore_user_profile.xml
  app/src/main/res/layout/activity_popup_window.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/bottom_sheet_layout.xml
  app/src/main/res/layout/cell_explore_found.xml
  app/src/main/res/layout/update_fullname.xml
  app/src/main/res/layout/update_profileimage.xml
  app/src/main/res/layout/update_username.xml
  app/src/main/res/values/themes.xml
  docs/demo/full name edit.gif
  docs/demo/v1.0.0-explore-and-follow-a-club.gif
  docs/demo/v1.0.0-explore-follow-and-unfollow-a-club.gif
  docs/demo/v1.0.0-explore-keyword-search-indifference.gif
  docs/squad-house-activity-class-included.uxf
  docs/squad-house-class-diagram.png
  docs/squad-house-class-diagram.uxf
  docs/wireframes/explore-club.png
  docs/wireframes/profile-editting.png
Labels: feature, frontend design

#63 Documentation, demo, minor bug fixes
  app/src/main/AndroidManifest.xml
Labels: bug, documentation, enhancement, frontend design

#65 Add RoomRoute and verified method of querying for RoomRoute availability
  app/src/main/java/com/pepetech/squadhouse/SquadHouseApplication.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/helpers/BottomSheetDialogActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/RoomRoute.java
  docs/demo/v1.0.0-room-route-query-proof-of-concept.gif
  docs/squad-house-room-activity-prototype.png
  docs/squad-house-room-activity-prototype.uxf
Labels: PR: work in progress, backend design, documentation, feature, priority: high

#68 Feature FollowingActivity via MyProfile
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreUserActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/adapters/ExploreUserAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Following/FollowingActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Following/adapters/FollowingAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/InterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/adapters/InnerInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/adapters/OuterInterestAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Settings/SettingsActivity.java
  app/src/main/res/layout/activity_explore_user_profile.xml
  app/src/main/res/layout/activity_interest.xml
  docs/demo/v1.0.0-explore-user-profile-following-state.gif
  docs/demo/v1.0.0-fix-view-following.gif
  docs/demo/v1.0.0-my-profile-following-activity-completion.gif
Labels: bug, feature, frontend design, priority: low

#71 Feature home feed
  app/build.gradle
  app/src/main/java/com/pepetech/squadhouse/activities/Explore/ExploreUserActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/FollowingActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeMultiViewAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/helpers/PhotoUploadBottomSheetDialogActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/helpers/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/Room.java
  app/src/main/res/layout/activity_following.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_photo_upload_dialog.xml
  docs/wireframes/homepage-hetero-recycler-view.png
Labels: enhancement, frontend design

#73 Feature voice call
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/ClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeMultiViewAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/InviteActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/RoomActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SetUpRoomActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/adapters/InviteAdapter.java
  app/src/main/java/com/pepetech/squadhouse/adapters/ParticipantAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Room.java
  app/src/main/java/com/pepetech/squadhouse/models/RoomRoute.java
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_room.xml
  app/src/main/res/layout/activity_set_up_room.xml
  app/src/main/res/layout/cell_call_participant.xml
  app/src/main/res/layout/cell_follower.xml
  build.gradle
Labels: bug, feature, frontend design, priority: high

#75 Feature club page merge conflict resolved
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/ClubInterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/MyInterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/MyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SettingsActivity.java
  app/src/main/res/layout/activity_club_interest.xml
  app/src/main/res/layout/activity_interest.xml
  app/src/main/res/layout/activity_settings.xml
Labels: frontend design

#77 update user profile's image
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/helpers/PhotoUploadBottomSheetDialogActivity.java
Labels: bug, feature

#79 Update Room.java
  app/src/main/java/com/pepetech/squadhouse/models/Room.java
Labels: backend design, bug

#81 Feature explore page
  app/src/main/res/layout/activity_explore.xml
Labels: enhancement

#80 My Profile package cleanup
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/MyProfileActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/adapters/MyClubsAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/fragments/BiographyBottomSheetDialog.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/fragments/PhotoUploadBottomSheetDialog.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/update/UpdateFullNameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/update/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/update/UpdateUsernameActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/ViewMyProfileActivity.java
  app/src/main/res/layout/activity_my_profile.xml
  app/src/main/res/layout/activity_popup_window.xml
  app/src/main/res/layout/activity_update_fullname.xml
  app/src/main/res/layout/activity_update_profile_image.xml
  app/src/main/res/layout/activity_update_username.xml
  app/src/main/res/layout/fragment_photo_upload_dialog.xml
  docs/demo/v1.0.0-profile-upload-bottom-sheet-refactored.gif
Labels: enhancement, frontend design

#83 Feature event and application launch icon
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/pepetech/squadhouse/SquadHouseApplication.java
  app/src/main/java/com/pepetech/squadhouse/activities/Event/EventActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Event/EventAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Event/EventCreateActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/RoomActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/Event.java
  app/src/main/res/drawable/ic_baseline_done_24.xml
  app/src/main/res/drawable/ic_baseline_post_add_24.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_outline_cancel_24.xml
  app/src/main/res/layout/activity_event.xml
  app/src/main/res/layout/activity_event_create.xml
  app/src/main/res/layout/cell_event.xml
  app/src/main/res/menu/menu_done_cancel.xml
  app/src/main/res/menu/menu_event.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: feature, frontend design

#87 Fix label formatting on firstname
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Login/SignUpActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/adapters/MyClubsAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/SetUpRoomActivity.java
  app/src/main/res/layout/activity_update_fullname.xml
Labels: enhancement

#93 Feature/club page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pepetech/squadhouse/activities/Club/ClubCreateActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Club/fragments/ClubPhotoUploadBottomSheetDialog.java
  app/src/main/java/com/pepetech/squadhouse/activities/ClubActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Interest/ClubInterestActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/adapters/MyClubsAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/fragments/UserPhotoUploadBottomSheetDialog.java
  app/src/main/java/com/pepetech/squadhouse/activities/MyProfile/update/UpdateProfileImageActivity.java
  app/src/main/java/com/pepetech/squadhouse/util/PhotoUploadBottomSheetDialog.java
  app/src/main/res/drawable/ic_baseline_add_photo_alternate_24.xml
  app/src/main/res/drawable/ic_baseline_navigate_next_24.xml
  app/src/main/res/layout/activity_club.xml
  app/src/main/res/layout/activity_club_create.xml
  docs/demo/v1.0.0-club-create.gif
Labels: feature, frontend design

#94 Feature/voice call participant
  app/src/main/java/com/pepetech/squadhouse/activities/RoomActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/SetUpRoomActivity.java
  app/src/main/java/com/pepetech/squadhouse/models/Room.java
  app/src/main/res/layout/activity_set_up_room.xml
  docs/demo/v1.0.0-voice-call-bug-fixed.gif
Labels: bug, feature

#95 Feature/event
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeFeedAdapter.java
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeMultiViewAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Event.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/cell_home_event.xml
  app/src/main/res/layout/cell_home_room_active.xml
  docs/demo/v1.0.0-hetero-view-recycler.gif
Labels: bug, feature, frontend design

#96 [Feature/event] update to poll for all Events scheduledFor a time greater (in the future) than the current date
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
Labels: enhancement

#97 Update title of home feed
  app/src/main/java/com/pepetech/squadhouse/activities/Home/HomeActivity.java
Labels: enhancement

#98 [Feature/club page]: Improve GUI
  app/src/main/res/layout/activity_club_create.xml
  app/src/main/res/layout/activity_set_up_room.xml
Labels: enhancement, frontend design

#99 [Feature/home feed]: Improve GUI
  app/src/main/java/com/pepetech/squadhouse/activities/Home/adapters/HomeMultiViewAdapter.java
  app/src/main/java/com/pepetech/squadhouse/models/Event.java
  app/src/main/res/layout/activity_event_create.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_interest.xml
  app/src/main/res/layout/cell_home_event.xml
  app/src/main/res/layout/cell_home_explore.xml
  app/src/main/res/layout/cell_home_room_active.xml
Labels: enhancement
